/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sstodev1;

/**
 *
 * @author Deniz Eryilmaz
 */
public class beagconv extends javax.swing.JFrame {

    /**
     * Creates new form beagconv
     */
    public beagconv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setActionCommand("toDecimal");

        jLabel1.setText("Decimal");

        jButton2.setText(">>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(">>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Gray");

        jLabel7.setText("BCD");

        jLabel8.setText("Excess-3");

        jLabel9.setText("Aiken");

        buttonGroup2.add(jCheckBox3);
        jCheckBox3.setText("Aiken");
        jCheckBox3.setActionCommand("aikento");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jCheckBox4);
        jCheckBox4.setText("Gray");
        jCheckBox4.setToolTipText("");
        jCheckBox4.setActionCommand("togray");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jCheckBox1);
        jCheckBox1.setText("BCD");
        jCheckBox1.setActionCommand("tbcdto");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jCheckBox2);
        jCheckBox2.setText("Excess-3");
        jCheckBox2.setActionCommand("toexcess3");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Aiken ve Gray çalışmıyor.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox4)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton2)
                        .addGap(41, 41, 41)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField5)
                    .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new mainPage().setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (bcdto == true){
             if(jTextField2.getText().equals("")) {
                jTextField1.setText("Baslangic degeri girilmedi.");
            
            }else{
            int t = bcdToDecimal(jTextField2.getText());
            String s = String.valueOf(t);
            jTextField1.setText(s);
            
            }
           
        }
        if (excess3 == true){
             if(jTextField2.getText().equals("")) {
                jTextField1.setText("Baslangic degeri girilmedi.");
            
            }else{
                String t = Excess3ToDecimal(jTextField2.getText());
                String s = String.valueOf(t);
                jTextField1.setText(s);
            }
           
        }
        if (aiken == true){
            if(jTextField2.getText().equals("")) {
                jTextField1.setText("Baslangic degeri girilmedi.");
            
            }else{
                String t = AikenToDecimal(jTextField2.getText());
                String s = String.valueOf(t);
                jTextField1.setText(s);
            }
        }
        if (gray == true){
             if(jTextField2.getText().equals("")) {
                jTextField1.setText("Baslangic degeri girilmedi.");
            
            }else{
                String t = GrayToDecimal(jTextField2.getText());
                String s = String.valueOf(t);
                jTextField1.setText(s);
            }    
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    if(jTextField1.getText().equals("")) {
    jTextField1.setText("Decimal degeri yok.");
    }else{
        String bcd = toBCD(Integer.parseInt(jTextField1.getText()));
        jTextField3.setText(bcd);       
        String ex3 = toExcess3(Integer.parseInt(jTextField1.getText()));
        jTextField4.setText(ex3);
        String aiken = toAiken(Integer.parseInt(jTextField1.getText()));
        jTextField5.setText(aiken);
        String gray = toGray(Integer.parseInt(jTextField1.getText()));
        jTextField10.setText(gray);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    boolean bcdto = false;
    boolean excess3 = false;
    boolean aiken = false;
    boolean gray = false;
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       bcdto = true;
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        excess3 = true;
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        aiken = true;
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        gray = true;
    }//GEN-LAST:event_jCheckBox4ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beagconv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beagconv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beagconv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beagconv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new beagconv().setVisible(true);
            }
        });
    }
    //--------------------------------------------------- To Decimal Kodlari ---------------------------------------------------------------------------------------------
    
    
    public static int bcdToDecimal(String s) 
    { 
        int len = s.length(); 
        int check = 0, check0 = 0; 
        int num = 0, sum = 0; 
        int mul = 1, rev = 0; 
  

        for(int i = len - 1; i >= 0; i--)  
        { 
  

            sum += (s.charAt(i) - '0') * mul; 
            mul *= 2; 
            check++; 

            if (check == 4 || i == 0)  
            { 
                if (sum == 0 && check0 == 0)  
            { 
               num = 1; 
               check0 = 1; 
            } 
                else
            { 
  

               num = num * 10 + sum; 
            } 
             
            check = 0; 
            sum = 0; 
            mul = 1; 
       } 
    } 

        while (num > 0)  
    { 
        rev = rev * 10 + (num % 10); 
        num /= 10; 
    } 
  
        if (check0 == 1) 
            return rev - 1; 
  
        return rev; 
    } 
      public static String Excess3ToDecimal(String s)
    {
        
        String data = s;
        data = data.replaceAll(" ", "");
        int a = bcdToDecimal(data);
        String output = new String();
        
        
       String temp = Integer.toString(a);
       int[] numarray = new int[temp.length()];
       for (int i = 0; i < temp.length(); i++)
       {
            numarray[i] = temp.charAt(i) - '0';
            numarray[i] -= 3;
            output = output+numarray[i];
       }          
        return output;
    }
      public static String AikenToDecimal(String s)
    {
        

        String output = new String();
        
        int a = Integer.valueOf(s);
       
        //00111
        int[] arraynum = String.valueOf(a).chars().map(Character::getNumericValue).toArray();
       // 0 0 1 1 1
       
        /**
        for (int i = 0; i < arraynum.length; i++){
            switch (arraynum[i]) { 
        case 0001: 
            binarystring  = "1"; 
            break; 
        case 0010: 
            binarystring  = "2"; 
            break; 
        case 0011: 
            binarystring  = "3"; 
            break; 
        case 0100: 
            binarystring  = "4; 
            break; 
        case 1011: 
            binarystring = "5"; 
            break; 
        case 1100: 
            binarystring  = "6"; 
            break; 
        case 1101: 
            binarystring = "7"; 
            break; 
        case 1110: 
            binarystring = "8"; 
            break; 
        case 1111: 
            binarystring  = "9"; 
            break; 
        case 0000: 
            binarystring  = "0"; 
            break; 
        default: 
            binarystring = null; 
        } 
        **/

        return output;
    }

        public static String GrayToDecimal(String s) {
            
            int gray = Integer.parseInt(s);
            int bin = 0;
            while (gray != 0) {
                int dec = gray - 1;
                bin ^= gray;
                bin ^= dec;
                gray &= dec;
            }
        int decimal = Integer.parseInt(Integer.toString(bin),2);
        return Integer.toString(decimal);

}
       
    
      
    
    //--------------------------------------- Decimalden diger kodlama turlerine -----------------------------------------------------------
    
    
    
       public static String toBCD(int num)
    {
        String BCD="";
        while(num!=0)
        {
        int t=num%10;
        String tBCD=Integer.toBinaryString(t);
        while(tBCD.length()<4)
            {
            tBCD="0"+tBCD;
            }
        BCD=tBCD+BCD;
        num/=10;
        }
        return BCD;
    }
       
        public static String toExcess3(int num)
    {
        String output = new String();;
        String numstring = String.valueOf(num);
        int[] arraynum = String.valueOf(num).chars().map(Character::getNumericValue).toArray();
        String[] binarycode =  new String[arraynum.length];
        
        
        for (int i = 0; i < arraynum.length; i++){
            arraynum[i] += 3;
            binarycode[i] = String.format("%4s", Integer.toBinaryString(arraynum[i])).replace(' ', '0');
            output += " " + binarycode[i]; 
        }  

        return  output;
    }
        
        
       public static String toAiken(int num)
    {
        
        int[] arraynum = String.valueOf(num).chars().map(Character::getNumericValue).toArray();
        String output = new String();
        String binarystring = new String();
        
        for (int i = 0; i < arraynum.length; i++){
                switch (arraynum[i]) { 
        case 1: 
            binarystring  = "0001"; 
            break; 
        case 2: 
            binarystring  = "0010"; 
            break; 
        case 3: 
            binarystring  = "0011"; 
            break; 
        case 4: 
            binarystring  = "0100"; 
            break; 
        case 5: 
            binarystring = "1011"; 
            break; 
        case 6: 
            binarystring  = "1100"; 
            break; 
        case 7: 
            binarystring = "1101"; 
            break; 
        case 8: 
            binarystring = "1110"; 
            break; 
        case 9: 
            binarystring  = "1111"; 
            break; 
        case 0: 
            binarystring  = "0000"; 
            break; 
        default: 
            binarystring = null; 
        } 
        output += " " + binarystring;       

        }  
        
            
        return output;
    }
      public static String toGray(int num)
    {      
        return String.valueOf(getGreyCode(num));
    }
    static String getGreyCode(int myNum, int numOfBits) {
        
        if (numOfBits == 1) {
            return String.valueOf(myNum);
        }

        if (myNum >= Math.pow(2, (numOfBits - 1))) {
            return "1" + getGreyCode((int)(Math.pow(2, (numOfBits))) - myNum - 1, numOfBits - 1);
        } else {
            return "0" + getGreyCode(myNum, numOfBits - 1);
            }
        }

    static String getGreyCode(int myNum) {

        int numOfBits = (int)(Math.log(myNum) / Math.log(2)) + 1;
        return getGreyCode(myNum, numOfBits);
    }
     
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
